# =============================================================================
# Docker Compose per Few-Shot Agent
# =============================================================================

version: '3.8'

services:
  all_in_one:
    build:
      context: .  # Assicurati che il Dockerfile sia nella stessa directory
      dockerfile: Dockerfile  # Specifica il nome del Dockerfile se necessario
    image: all_in_one:latest  # Sostituisci con l'immagine Docker corretta
    container_name: all_in_one
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - models_cache:/models_cache
      - hf_cache:/hf_cache
    ports:
      - "8071:8071"  # Modifica la porta se necessario
    networks:
      - all_in_one_network
    runtime: nvidia  # Assicurati di avere il runtime NVIDIA configurato
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Assicurati che il container possa accedere alla GPU
# Volumi nominati per persistenza
volumes:
  models_cache:
    driver: local
  hf_cache:
    driver: local

# Network per eventuale espansione futura
networks:
  all_in_one_network:
    driver: bridge