# =============================================================================
# Docker Compose per Few-Shot Agent
# =============================================================================

version: '3.8'

services:
  green_server3:
    build:
      context: .  # Assicurati che il Dockerfile sia nella stessa directory
      dockerfile: Dockerfile  # Specifica il nome del Dockerfile se necessario
    image: green3:latest  # Sostituisci con l'immagine Docker corretta
    container_name: green_server3
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - models_cache:/models_cache
      - hf_cache:/hf_cache
    ports:
      - "8075:8075"  # Modifica la porta se necessario
    networks:
      - green_network3
    runtime: nvidia  # Assicurati di avere il runtime NVIDIA configurato
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Assicurati che il container possa accedere alla GPU
# Volumi nominati per persistenza
volumes:
  models_cache:
    driver: local
  hf_cache:
    driver: local

# Network per eventuale espansione futura
networks:
  green_network3:
    driver: bridge