# =============================================================================
# Docker Compose per Few-Shot Agent
# =============================================================================

version: '3.8'

services:
  green_server2:
    build:
      context: .  # Assicurati che il Dockerfile sia nella stessa directory
      dockerfile: Dockerfile  # Specifica il nome del Dockerfile se necessario
    image: green2:latest  # Sostituisci con l'immagine Docker corretta
    container_name: green_server2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - models_cache:/models_cache
      - hf_cache:/hf_cache
    ports:
      - "8072:8072"  # Modifica la porta se necessario
    networks:
      - green_network2
    runtime: nvidia  # Assicurati di avere il runtime NVIDIA configurato
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Assicurati che il container possa accedere alla GPU
# Volumi nominati per persistenza
volumes:
  models_cache:
    driver: local
  hf_cache:
    driver: local

# Network per eventuale espansione futura
networks:
  green_network2:
    driver: bridge