# =============================================================================
# Docker Compose per Gemma Few-Shot Agent
# =============================================================================

version: '3.8'

services:
  magenta_server:
    build:
      context: .  # Assicurati che il Dockerfile sia nella stessa directory
      dockerfile: Dockerfile  # Specifica il nome del Dockerfile se necessario
    image: magenta:latest  # Sostituisci con l'immagine Docker corretta
    container_name: magenta_agent
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - models_cache:/app/models
      - hf_cache:/app/cache
    ports:
      - "8074:8074"  # Modifica la porta se necessario
    networks:
      - magenta_network
    runtime: nvidia  # Assicurati di avere il runtime NVIDIA configurato
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Assicurati che il container possa accedere alla GPU
# Volumi nominati per persistenza
volumes:
  models_cache:
    driver: local
  hf_cache:
    driver: local

# Network per eventuale espansione futura
networks:
  magenta_network:
    driver: bridge